// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADUFghbbN4Xzn0OXQqHkyAauMRSGdquVI',
    appId: '1:470402961821:web:c965012d287371147d1f74',
    messagingSenderId: '470402961821',
    projectId: 'employee-db-c92f9',
    authDomain: 'employee-db-c92f9.firebaseapp.com',
    databaseURL: 'https://employee-db-c92f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-c92f9.firebasestorage.app',
    measurementId: 'G-NV7RKCCWV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk-vTX3nOMbpt2enG0O-D4OaruRhNYANs',
    appId: '1:470402961821:android:dae3e3c041a138467d1f74',
    messagingSenderId: '470402961821',
    projectId: 'employee-db-c92f9',
    databaseURL: 'https://employee-db-c92f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-c92f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA355PzcBQmPGnyjWkCW6KPEVtl6_193Ug',
    appId: '1:470402961821:ios:c99b79b545dc5be57d1f74',
    messagingSenderId: '470402961821',
    projectId: 'employee-db-c92f9',
    databaseURL: 'https://employee-db-c92f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-c92f9.firebasestorage.app',
    iosBundleId: 'com.example.employeeMarcelalpinsanty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA355PzcBQmPGnyjWkCW6KPEVtl6_193Ug',
    appId: '1:470402961821:ios:c99b79b545dc5be57d1f74',
    messagingSenderId: '470402961821',
    projectId: 'employee-db-c92f9',
    databaseURL: 'https://employee-db-c92f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-c92f9.firebasestorage.app',
    iosBundleId: 'com.example.employeeMarcelalpinsanty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADUFghbbN4Xzn0OXQqHkyAauMRSGdquVI',
    appId: '1:470402961821:web:2e6ad8d4596063f67d1f74',
    messagingSenderId: '470402961821',
    projectId: 'employee-db-c92f9',
    authDomain: 'employee-db-c92f9.firebaseapp.com',
    databaseURL: 'https://employee-db-c92f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-c92f9.firebasestorage.app',
    measurementId: 'G-J3R0NCN8YB',
  );
}
